name: search_restaurants
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
 sdk: ">=2.17.6 <3.0.0"

dependencies:
 another_flushbar: ^1.10.29
 cloud_firestore: ^3.1.12
 cupertino_icons: ^1.0.2
 dartz: ^0.10.1
 equatable: ^2.0.3
 firebase_auth: ^3.6.1
 firebase_core: ^1.20.0
 flutter:
  sdk: flutter
 flutter_bloc: ^8.0.1
 get_it: ^7.2.0
 injectable: ^1.5.3
 utils:
  git:
   url: https://github.com/thomasviana/utils.git
   ref: main
 uuid: ^3.0.6

dev_dependencies:
 build_runner: ^2.2.0

 flutter_lints: ^2.0.0
 flutter_test:
  sdk: flutter
 injectable_generator: ^1.5.4

flutter:
 uses-material-design: true
