// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcV-NUs-rhgWWuEeI_aqge5SUe0gdnQuA',
    appId: '1:140672872644:android:e4efd10b087872d950d991',
    messagingSenderId: '140672872644',
    projectId: 'search-restaurants-flutter',
    storageBucket: 'search-restaurants-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4qHRKkhJZn6yWhYeAlg5z9bmKIRAmb_w',
    appId: '1:140672872644:ios:480503bd7fb5eab950d991',
    messagingSenderId: '140672872644',
    projectId: 'search-restaurants-flutter',
    storageBucket: 'search-restaurants-flutter.appspot.com',
    iosClientId: '140672872644-3pl41tqur03g9tc5dj6ndlukt07ve59e.apps.googleusercontent.com',
    iosBundleId: 'com.example.searchRestaurants',
  );
}
